# Note: these are somewhat minimal requirements. Features such as prometheus service monitoring
# or log streaming are in the main templates, but must be explicitly enabled in your override-values.yaml
apiVersion: v2
name: integration-manager-umbrella
version: 1.0.3
appVersion: 2.0.5
description: Installs Integration Manager, DataCloud Worker, NGINX Ingress, RabbitMQ, MySQL
type: application
keywords:
  - Integration Manager
  - DataCloud Worker
  - NGINX Ingress
  - RabbitMQ
  - MySQL

dependencies:
  # Both longhorn and minio are used for storage, longhorn seems to be more robust
  - name: longhorn
    version: "1.5.5"
    repository: "https://charts.longhorn.io"
    condition: longhorn.enabled
  - name: minio
    version: 14.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: ingress-nginx
    version: 4.10.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: rabbitmq
    version: 14.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: mysql
    version: 10.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: integration-manager
    repository: https://s3.amazonaws.com/actian-datacloud-helm-charts
    version: 1.2.86
    condition: integration-manager.enabled
  # Template information for the integration-manager-worker chart can be found here
  # https://github.com/ActianCorp/integration-manager-worker-helm-chart/tree/master
  - name: integration-manager-worker
    repository: https://s3.amazonaws.com/actian-datacloud-helm-charts
    version: 1.2.63
    condition: integration-manager-worker.enabled
