apiVersion: v2
name: integration-manager-umbrella
version: 1.0.0
appVersion: 2.0.5
description: Installs Integration Manager, DataCloud Worker, NGINX Ingress, RabbitMQ, MySQL
type: application
keywords:
  - Integration Manager
  - DataCloud Worker
  - NGINX Ingress
  - RabbitMQ
  - MySQL

dependencies:
  - name: integration-manager
    repository: https://s3.amazonaws.com/actian-datacloud-helm-charts
    version: 1.2.60
    condition: integration-manager.enabled
  - name: integration-manager-worker
    repository: https://s3.amazonaws.com/actian-datacloud-helm-charts
    version: 1.2.30
    condition: integration-manager-worker.enabled
  - name: ingress-nginx
    version: 3.35.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled
  - name: rabbitmq
    version: 8.28.1
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: mysql
    version: 8.8.23
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
  - name: minio
    version: 10.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
